### PR TITLE
WIP 2019 Redesign

### PR DESCRIPTION
**Pull request by danivovich**
### TODO
- [x] Case Study text
- [x] Client logos on http://127.0.0.1:4000/case-studies
- [x] Read the case study links on http://127.0.0.1:4000/
- [ ] Test contact form http://127.0.0.1:4000/contact
- [ ] Mailing list signup
- [x] Content on http://127.0.0.1:4000/phoenix-and-elixir
- [x] Content on http://127.0.0.1:4000/react-native
- [ ] Check quotes and links in footers
- [ ] Check that Google Analytics is flowing
- [ ] Randomizable client quotes
- [ ] Randomizable read this other case study // for bottom of case study pages

### Decisions to make
- [ ] We had mouseflow on the old site, but as far as I know we aren't using it
- [ ] Do we need any UTM source or other items on outbound links?
- [x] BWIT or Apprentice carryover?
- [x] Any outbound links on http://127.0.0.1:4000/community
- [ ] Any outbound links on http://127.0.0.1:4000/team
- [ ] Which case studies to include, which ones to feature on /case-studies
- [ ] Which logos do we want to feature in that top bar on the home page?

### CODE REVIEW

**Comment by danivovich** [comment]
@rozerosie @yflicker This is definitely not ready to merge, lots of things still missing or incomplete. I tried to build a reasonable list in the description for this PR.

Should be all set up enough that it can be iterated on pretty easily now.

**Comment by rozerosie** [comment]
@danivovich @yflicker Take a look a this draft of a case study page: 
        smartlogic.github.com/case-study/ncqa-test.html

If y'all feel good about it I'll replicate across the case studies

**Comment by danivovich** [comment]
@rozerosie Looks good, with a few items:
- Seems a bit off-center with the left justification and right gutter, that said, to go full page width might be wrong, and centered doesn't feel right for our general approach elsewhere, so this might be the best option, and might not be as bad considering the next item:
- The font size is also small compared to the main paragraph font on other pages.

**Comment by danivovich** [comment]
@rozerosie those last few changes look good

**Comment by rozerosie** [comment]
similar draft on the technology pages - take a look at the /react-native page @danivovich @yflicker

**Comment by yflicker** [comment]
NCQA case study:
* wrt case studies, when i had my browser window open to the full width of my screen (1280px width) i was at first confused why the content didn't span the entire width of the window, but to Dan's point, i agree, going full width could allow the reader to get lost in the content
* on the other side of the spectrum, when i make my browser window as slim as possible, the text abuts the right side of the window — can we put in padding or similar?
* can we put client logos somewhere on the case study pages?
* i much prefer the presentation of the folio image (images/contents/folio-screenshot.png) and BWT image (images/contents/water-taxi-screenshot.png) — i like putting the images in the context of a laptop or mobile phone. would it be possible for the NCQA and other images in the case study context or am i not thinking about something?

technology:
* i wonder if there's anything we can do with the hero-right on that page — an image or something. i think we talked about it and nothing came to mind, but if we can think of something, it'd be great to use that white space somehow. kind of like on the case-studies page.
* can we make the four headings right under the hero at the top (Embrace Open Source ... Widely-Adopted and) bold. i don't want to screw up other pages, but i accomplished this for this specific page by removing font-weight: 400 from .horizontal-list__item-text-head p and adding font-weight: bold to horizontal-list__item-text-head (guess the font-weight: bold can go on the p tag within that element). without the boldness the heading there loses distinction from the description that follows
* can we put text-decoration: underline back onto the links for Elixir/Phoenix, React Native, Ruby on Rails (when that link comes)? i knew they were links but i don't think it would have otherwise been obvious to me.

**Comment by yflicker** [comment]
With respect to 
* Any outbound links on /team — Dan are you referring to giving folks a space to put a small about me blurb / links to other sites (e.g. twitter or personal blog or whatever)
* This may address your question on outbound links on /community, but perhaps we have the BWiT and Apprentice link to /bwit and /apprentice, carry that content over, and put a large noticeable message at the top of each of those pages explaining the programs are over but we're leaving the content up for others to reference?

**Comment by rozerosie** [comment]
case study / technology pages body width:
- Readability definitely suffers when you get super long line lengths, I wanted to try to keep it from getting unwieldy if the window was super wide
- Agree about adding the padding on the right, makes sense to me

case studies:
- screenshots - right yes I had forgotten about putting screenshots on device mocks, I can make that happen. do we want to move all screenshots to device framing? it's not that hard but will take a bit of time.
- do the case studies we have listed there seem like the right ones? think we included too many or too few? think we're featuring the right ones? I made a best guess at that earlier in the design phase. at a minimum I will probably add NCQA to the featured list, bump order up down, and unlist zipmark

technology 
- subheaders bold - no problem. do we want to do the same for the similarly formatted subheads on the method page?
- header image - i think the fork icon might work well there, i'll give that a shot; otherwise we can pick another device screenshot we like and put it on a device
- the method page also doesn't have a header image, are we okay with that or do we want to try to add something there as well?

community links / pages
- i think it's good to keep the bwit and apprentice pages up; i like your idea to add clarifying time scope text; I think it also would be good to add relevant press links.

**Comment by rozerosie** [comment]
@danivovich @yflicker take a look at the /react-native page, I center aligned the content (but left the text left-aligned); does this feel more intentional / balanced?

**Comment by rozerosie** [comment]
Have the cases studies updated using new site styling. Still need to update screenshots, that'll be a separate process.

I am seeing a weird thing where some elements are deciding to be next to each other; this is most clear at http://127.0.0.1:4000/case-study/foliocollaborative where the H2 at the top of the page is for some reason to the left of the UL that should be below it. The page styling that I'm using for the case studies etc also seems to put elements next to each other when the page is super wide; idk why it's doing this or particularly how to fix it.

**Comment by rozerosie** [comment]
Think I have all the pages styled and linked up; I still have a number of cleanup tasks but just wanted to give a quick update. Next on my list is to put all the screenshots onto device mockups.

In case you want to see my list of to-do's (it's too messy to list here) it's on asana here: https://app.asana.com/0/1115951736870922/list

**Comment by danivovich** [comment]
@rozerosie This is looking great! 💯

**Comment by rozerosie** [comment]
Case studies page and screenshots mostly good to go:
- Updated most screenshots to be on-device
- Haven't done so for case studies we aren't listing on the /case-studies page 
- Also left kinglet screens alone b/c of the unusual form factor _(400x400 isn't going to crop nicely onto any device - wasn't sure if what they have up now was built by us or no, if yes, I can pull new screenshots to use)_. 
- Also updated copy on case studies page, so the blurbs are coherent and consistent
- Need to decide which logos to include at the bottom of the page - pinged Yair for feedback on which to include in that list

Two more to-do's before we have an MVP, IMO:
- thank you page for contact us
- a nav style that doesn't put company logos offscreen (that style makes sense for screenshots but is a no go for logos imo)

**Comment by yflicker** [comment]
@rozerosie i went through that spreadsheet of client logos and gave feedback there. small piece of feedback: can we increase the hit area on the three links / buttons at the top right? Case Studies, Method, Technology. maybe increase the padding and decrease margin (or whatever is causing the spacing there). As we start approaching the end here lmk if there is a better way to provide such feedback.

**Comment by rozerosie** [comment]
@yflicker I think this is okay as a thread for comments; I'm tracking a bunch of details in Asana, more than really would fit cleanly here. If we find that there are a lot of tweaks or features that we want to organize, I could set up a trello board. Might be a good way for us to prioritize and make an ordered backlog of future improvements.

**Comment by yflicker** [comment]
👍 @rozerosie @danivovich I'd say let's merge this in!

**Pull request merged**
